# configuration parsing starts here
defaults:
  - experiment: video_latent_learning # train the VAE first stage
  - dataset: minecraft # Minecraft dataset configuration
  - algorithm: image_vae # Image VAE trainer
  - optional dataset_experiment: ${dataset}_${experiment} # optional yaml file in configurations/dataset_experiment folder, overrides algorithm and experiment configurations that are dataset and experiment dependent
  - cluster: null # optional, cluster yaml file name in configurations/cluster folder. Leave null for local compute

debug: false # global debug flag will be passed into configuration of experiment, dataset and algorithm

wandb:
  entity: local # placeholder so training does not error even when disabled
  project: dfot # wandb project name; if not provided, defaults to root folder name [fixme]
  mode: online # disable wandb entirely

resume: null # wandb run id to resume logging and loading checkpoint from
load: null # wanmdb run id containing checkpoint or a path to a checkpoint file 